services:
    web:
        container_name: web_app_nginx
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        networks:
            - internal_net_web
    php:
        container_name: web_app_php
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        expose:
            -   "9000"
        networks:
            - internal_net_web
    mysql:
        container_name: web_app_db
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?Variable not set}
            - MYSQL_USER=${MYSQL_USER?Variable not set}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}
            - MYSQL_DATABASE=${MYSQL_DATABASE?Variable not set}
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - internal_net_web
volumes:
    mysqldata: {}

networks:
    internal_net_web:
        driver: bridge
